default:
  ## Run tests with most recent golang version to take advantage of any perf
  ## improvements.
  image: golang:latest
  before_script:
    - mkdir -p .cache/gocache
    - export PATH=$PATH:$CI_PROJECT_DIR/.cache/bin/
    - export GOPATH="$CI_PROJECT_DIR/.cache"
  artifacts:
    name: "SiaTesting-$CI_JOB_NAME"
    paths:
      - $CI_PROJECT_DIR/SiaTesting
      - $CI_PROJECT_DIR/cover/cover.out
    when: always
  after_script:
    - cp -R /tmp/SiaTesting $CI_PROJECT_DIR/SiaTesting

 
stages:
  - lint
  - test
  - deploy

lint:
  stage: lint
  cache:
    key: lint-cache
    paths:
      - .cache
  script: 
    ## This is the recommended way to install golang-ci lint.
    - wget -O- -nv https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.21.0
    - ./bin/golangci-lint run --disable-all --enable=vet --enable=gofmt --deadline=600s ./...
    - export GOCACHE=$CI_PROJECT_DIR/.cache/gocache
    - make test

build:
  stage: lint
  ## go 1.13 is the minimum accepted version for building Sia.
  image: golang:1.13
  artifacts:
    name: "Binaries"
    paths:
      - $CI_PROJECT_DIR/artifacts
  script:
    - ./build.sh

legacy-tests:
  stage: test
  cache:
    key: legacy-cache
    paths:
      - .cache
  except:
    - schedules
  script: 
    - make test-long pkgs="./node ./node/api ./node/api/server" run=.

package-tests:
  stage: test
  cache:
    key: package-cache
    paths:
      - .cache
  except:
    - schedules
  script: 
    - make test-long run=. pkgs="./build ./cmd/siac ./cmd/siad ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/filesystem ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/renter/siadir ./modules/renter/siafile ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"

siatest-tests:
  stage: test
  cache:
    key: integration-cache
    paths:
      - .cache
  except:
    - schedules
  script:
    - make test-long run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/host ./siatest/miner ./siatest/transactionpool ./siatest/wallet"

siatest-renter-tests:
  stage: test
  except:
    - schedules
  cache:
    key: siatest-renter-tests-cache
    paths:
      - .cache
  script:
    - apt-get update
    - apt-get install -y fuse
    - make test-long run=. pkgs="./siatest/renter ./siatest/renter/contractor ./siatest/renter/hostdb ./siatest/renterhost"

legacy-tests-nightly:
  stage: test
  only:
    - schedules
  script: 
    - make test-vlong pkgs="./node ./node/api ./node/api/server" run=.

package-tests-nightly:
  stage: test
  only:
    - schedules
  script: 
    - make test-vlong run=. pkgs="./build ./cmd/siac ./cmd/siad ./compatibility ./crypto ./encoding ./modules ./modules/consensus ./modules/explorer ./modules/gateway ./modules/host ./modules/host/contractmanager ./modules/renter ./modules/renter/contractor ./modules/renter/filesystem ./modules/renter/hostdb ./modules/renter/hostdb/hosttree ./modules/renter/proto ./modules/miner ./modules/wallet ./modules/transactionpool ./persist ./sync ./types"

siatest-tests-nightly:
  stage: test
  only:
    - schedules
  script:
    - make test-vlong run=. pkgs="./siatest ./siatest/consensus ./siatest/daemon ./siatest/gateway ./siatest/host ./siatest/miner ./siatest/transactionpool ./siatest/wallet"

siatest-renter--tests-nightly:
  stage: test
  only:
    - schedules
  script:
    - apt-get update
    - apt-get install -y fuse
    - make test-vlong run=. pkgs="./siatest/renter ./siatest/renter/contractor ./siatest/renter/hostdb ./siatest/renterhost"
