name: Test

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
      - name: lint
        uses: golangci/golangci-lint-action@v3
      - name: analyze
        run: |
          go get gitlab.com/NebulousLabs/analyze
          make analyze
      - name: gofmt 
        run: make fmt
      - name: go vet
        run: make vet
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    needs: [ lint ]
    steps:
      - uses: actions/checkout@v2
      - name: test
        uses: n8maninger/action-golang-test@v1
        with:
          args: "-race;-failfast;-tags=testing debug netgo"